/**
 * Static IATA airline code → name lookup.
 * Eliminates runtime API calls to FR24 /api/static/airlines.
 */

const AIRLINES: Record<string, string> = {
  // ── Major global carriers ─────────────────────────────
  AA: "American Airlines",
  AC: "Air Canada",
  AF: "Air France",
  AI: "Air India",
  AM: "Aeroméxico",
  AR: "Aerolíneas Argentinas",
  AS: "Alaska Airlines",
  AT: "Royal Air Maroc",
  AV: "Avianca",
  AY: "Finnair",
  AZ: "ITA Airways",
  BA: "British Airways",
  BI: "Royal Brunei Airlines",
  BR: "EVA Air",
  BT: "airBaltic",
  CA: "Air China",
  CI: "China Airlines",
  CM: "Copa Airlines",
  CX: "Cathay Pacific",
  CZ: "China Southern Airlines",
  DL: "Delta Air Lines",
  EI: "Aer Lingus",
  EK: "Emirates",
  ET: "Ethiopian Airlines",
  EW: "Eurowings",
  EY: "Etihad Airways",
  F9: "Frontier Airlines",
  FI: "Icelandair",
  FJ: "Fiji Airways",
  GA: "Garuda Indonesia",
  GF: "Gulf Air",
  HA: "Hawaiian Airlines",
  HU: "Hainan Airlines",
  IB: "Iberia",
  JL: "Japan Airlines",
  JQ: "Jetstar Airways",
  KA: "Cathay Dragon",
  KE: "Korean Air",
  KL: "KLM Royal Dutch Airlines",
  KQ: "Kenya Airways",
  LA: "LATAM Airlines",
  LH: "Lufthansa",
  LO: "LOT Polish Airlines",
  LX: "SWISS",
  ME: "Middle East Airlines",
  MF: "Xiamen Airlines",
  MH: "Malaysia Airlines",
  MS: "EgyptAir",
  MU: "China Eastern Airlines",
  NH: "All Nippon Airways",
  NK: "Spirit Airlines",
  NZ: "Air New Zealand",
  OA: "Olympic Air",
  OK: "Czech Airlines",
  OM: "MIAT Mongolian Airlines",
  OS: "Austrian Airlines",
  OU: "Croatia Airlines",
  OZ: "Asiana Airlines",
  PC: "Pegasus Airlines",
  PG: "Bangkok Airways",
  PK: "Pakistan International Airlines",
  PR: "Philippine Airlines",
  PS: "Ukraine International Airlines",
  QF: "Qantas",
  QR: "Qatar Airways",
  RJ: "Royal Jordanian",
  RO: "TAROM",
  SA: "South African Airways",
  SK: "SAS Scandinavian Airlines",
  SN: "Brussels Airlines",
  SQ: "Singapore Airlines",
  SU: "Aeroflot",
  SV: "Saudia",
  TG: "Thai Airways",
  TK: "Turkish Airlines",
  TP: "TAP Air Portugal",
  UA: "United Airlines",
  UL: "SriLankan Airlines",
  UX: "Air Europa",
  VA: "Virgin Australia",
  VN: "Vietnam Airlines",
  VS: "Virgin Atlantic",
  VY: "Vueling",
  WN: "Southwest Airlines",
  WS: "WestJet",
  WY: "Oman Air",
  ZI: "Aigle Azur",

  // ── Low-cost / regional (Asia-Pacific) ────────────────
  "3K": "Jetstar Asia",
  "5J": "Cebu Pacific",
  "7C": "Jeju Air",
  AK: "AirAsia",
  BL: "Pacific Airlines",
  BX: "Air Busan",
  D7: "AirAsia X",
  DD: "Nok Air",
  FD: "Thai AirAsia",
  GK: "Jetstar Japan",
  HO: "Juneyao Airlines",
  IT: "Tigerair Taiwan",
  IX: "Air India Express",
  JW: "Vanilla Air",
  LJ: "Jin Air",
  MM: "Peach Aviation",
  OD: "Malindo Air",
  QZ: "Indonesia AirAsia",
  RS: "Air Seoul",
  SC: "Shandong Airlines",
  SL: "Thai Lion Air",
  TW: "T'way Air",
  UO: "HK Express",
  VJ: "VietJet Air",
  VZ: "Thai Vietjet Air",
  XJ: "Thai AirAsia X",
  ZE: "Eastar Jet",
  ZH: "Shenzhen Airlines",

  // ── Low-cost / regional (Americas & Europe) ───────────
  "4O": "Interjet",
  "6E": "IndiGo",
  A3: "Aegean Airlines",
  B6: "JetBlue Airways",
  DE: "Condor",
  DY: "Norwegian Air Shuttle",
  FR: "Ryanair",
  G3: "GOL Linhas Aéreas",
  HV: "Transavia",
  IW: "Wings Air",
  JU: "Air Serbia",
  LS: "Jet2.com",
  NO: "Neos",
  QS: "SmartWings",
  TO: "Transavia France",
  U2: "easyJet",
  W6: "Wizz Air",
  WO: "Swoop",
  XT: "Indonesia AirAsia X",

  // ── Cargo / specialty (sometimes on passenger feeds) ──
  "5X": "UPS Airlines",
  FX: "FedEx Express",
  CV: "Cargolux",
  PO: "Polar Air Cargo",

  // ── Chinese regionals ─────────────────────────────────
  "3U": "Sichuan Airlines",
  "8L": "Lucky Air",
  "9C": "Spring Airlines",
  BK: "Okay Airways",
  CN: "Grand China Air",
  DR: "Ruili Airlines",
  DZ: "Donghai Airlines",
  EU: "Chengdu Airlines",
  FM: "Shanghai Airlines",
  GJ: "Loong Air",
  GS: "Tianjin Airlines",
  GT: "Air Guilin",
  GX: "Guangxi Beibu Gulf Airlines",
  GY: "Colorful Guizhou Airlines",
  HX: "Hong Kong Airlines",
  HY: "Uzbekistan Airways",
  JD: "Beijing Capital Airlines",
  KN: "China United Airlines",
  KY: "Kunming Airlines",
  NS: "Hebei Airlines",
  PN: "West Air",
  QW: "Qingdao Airlines",
  TV: "Tibet Airlines",
  Y8: "Suparna Airlines",
  ZJ: "Shenzhen Donghai Airlines",

  // ── Korean and Japanese regionals ─────────────────────
  BC: "Skymark Airlines",
  FW: "Ibex Airlines",
  HD: "Air Do",
  IJ: "Spring Airlines Japan",
  KJ: "Air Incheon",
  NU: "Japan Transocean Air",
  RF: "Aero K",

  // ── Middle-East / Africa regionals ────────────────────
  "8Q": "Onur Air",
  "9W": "Jet Airways",
  G9: "Air Arabia",
  HM: "Air Seychelles",
  J9: "Jazeera Airways",
  OV: "SalamAir",
  WB: "RwandAir",
  XY: "flynas",

  // ── Additional coverage ───────────────────────────────
  AD: "Azul Brazilian Airlines",
  AH: "Air Algérie",
  DG: "Cebgo",
  EB: "Wamos Air",
  GI: "Gail Force Aero",
  H1: "Hahn Air",
  JC: "Japan Air Commuter",
  KC: "Air Astana",
  LG: "Luxair",
  MD: "Air Madagascar",
  MI: "SilkAir",
  MJ: "Myway Airlines",
  NX: "Air Macau",
  PX: "Air Niugini",
  S7: "S7 Airlines",
  ST: "Germania",
  TN: "Air Tahiti Nui",
  TR: "Scoot",
  TT: "Tigerair Australia",
  TZ: "Scoot Tigerair",
  UB: "Myanmar National Airlines",
  UK: "Vistara",
  UP: "Bahamasair",
  UT: "UTair",
  WM: "Windrose Airlines",
  WW: "WOW air",
  XL: "LATAM Airlines Ecuador",
  YP: "Air Premia",
  ZG: "ZIPAIR Tokyo",
};

/**
 * Extract the 2-character IATA airline prefix from a flight number.
 * Handles alphanumeric codes like "7C1405" or "3K234".
 */
export function extractIataPrefix(flight?: string): string | null {
  if (!flight || flight.length < 3) return null;
  const match = flight.match(/^([A-Z0-9]{2})\d/);
  return match ? match[1] : null;
}

/** Look up airline name by IATA code. Returns undefined if unknown. */
export function airlineName(iata: string): string | undefined {
  return AIRLINES[iata];
}

/** Get the full set of known IATA codes (useful for logo download scripts). */
export function knownIataCodes(): string[] {
  return Object.keys(AIRLINES);
}
